// seeders/YYYYMMDDHHMMSS-initial-data.js
'use strict';

const { Category, Service, Product, User, Professional, Booking, BookingItem, ServiceRequest } = require('../database/models'); // ajusta según tu estructura

module.exports = {
    async up(queryInterface, Sequelize) {
        // ------------------------------------------------------
        // 1. CATEGORIES
        // ------------------------------------------------------
        await Category.bulkCreate([
            { id: 'cat_001', slug: 'climatizacion', name: 'Climatización', description: 'Aires acondicionados, ventiladores, estufas y calefactores', icon: '❄️', is_active: true, order: 1, created_at: '2025-01-01 00:00:00', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_002', slug: 'herramientas', name: 'Herramientas', description: 'Herramientas manuales, eléctricas e industriales', icon: '🔧', is_active: true, order: 2, created_at: '2025-01-01 00:00:00', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_003', slug: 'ferreteria', name: 'Ferretería', description: 'Tornillos, bulones, anclajes y fijaciones', icon: '🔩', is_active: true, order: 3, created_at: '2025-01-01 00:00:00', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_004', slug: 'iluminacion', name: 'Iluminación', description: 'Lámparas, spots, tiras LED y artefactos de iluminación', icon: '💡', is_active: true, order: 4, created_at: '2025-01-01 00:00:00', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_005', slug: 'plomeria', name: 'Plomería', description: 'Cañerías, llaves de paso, termotanques y sanitarios', icon: '🚿', is_active: true, order: 5, created_at: '2025-01-01 00:00:00', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_006', slug: 'electricidad', name: 'Electricidad', description: 'Cables, tableros, disyuntores y materiales eléctricos', icon: '⚡', is_active: true, order: 6, created_at: '2025-01-01 00:00:00', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_007', slug: 'pinturas', name: 'Pinturas', description: 'Pinturas, esmaltes, barnices y accesorios de pintura', icon: '🎨', is_active: true, order: 7, created_at: '2025-01-01 00:00:00', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_008', slug: 'construccion', name: 'Construcción', description: 'Cemento, ladrillos, cerámicos y materiales de obra', icon: '🏗️', is_active: true, order: 8, created_at: '2025-01-01 00:00:00', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_009', slug: 'manicura', name: 'Manicura', description: '"Corte de uñas"\n"Esmaltado"\n"Permanentes"', icon: '💅', is_active: true, order: 9, created_at: '2026-04-08 22:44:58', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_010', slug: 'capacitaciones', name: 'Capacitaciones', description: 'Cursos con certificaciones brindadas por profesionales academicos expertos es su materia.', icon: '👨‍🏫', is_active: true, order: 10, created_at: '2026-04-08 22:44:58', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_011', slug: 'masajista', name: 'Masajista', description: 'Profesionales con titulos habilitantes para desarrollar terapias corporales. Relax asegurado.', icon: '💆', is_active: true, order: 11, created_at: '2026-04-10 15:46:41', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_012', slug: 'artilugios', name: 'Artilugios', description: 'Objetos realizados únicamente para funciones especificas.', icon: '🃏', is_active: true, order: 12, created_at: '2026-04-14 21:54:08', updated_at: '2026-04-27 15:02:07' },
            { id: 'cat_013', slug: 'motores', name: 'Motores', description: 'Motores', icon: '🃏', is_active: true, order: 13, created_at: '2026-04-27 14:58:17', updated_at: '2026-04-27 15:02:07' }
        ], { ignoreDuplicates: true });

        // ------------------------------------------------------
        // 2. SERVICES
        // ------------------------------------------------------
        await Service.bulkCreate([
            { id: 'serv_001', name: 'Electricista', slug: 'electricista', description: 'Instalación, reparación y mantenimiento de sistemas eléctricos residenciales y comerciales. Incluye tableros, cableado, disyuntores y sistemas de iluminación.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":["Curso básico de electricidad"]},{"nivel":"1-2 años","requisitos":["Experiencia comprobable","Curso de seguridad eléctrica"]},{"nivel":"3-5 años","requisitos":["Matrícula habilitante","Certificado de altura"]},{"nivel":"6-10 años","requisitos":["Matrícula profesional","Especialización en alta tensión"]},{"nivel":"+10 años","requisitos":["Matrícula profesional","Certificación en gestión de proyectos"]}]'), certification_required: true, is_featured: true, is_active: true, base_price: null, hourly_price: null, created_at: '2026-01-01 00:00:00', updated_at: '2026-04-15 15:45:59' },
            { id: 'serv_002', name: 'Plomero / Gasista', slug: 'plomero-gasista', description: 'Instalación y reparación de sistemas de agua fría/caliente, desagües, termotanques, calefones y redes de gas natural.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":["Curso básico de plomería"]},{"nivel":"1-2 años","requisitos":["Experiencia comprobable","Curso de gasista"]},{"nivel":"3-5 años","requisitos":["Matrícula de gasista","Certificado de instalador"]},{"nivel":"6-10 años","requisitos":["Matrícula profesional","Especialización en termomecánica"]},{"nivel":"+10 años","requisitos":["Matrícula profesional","Certificación en eficiencia energética"]}]'), certification_required: true, is_featured: true, is_active: true, base_price: 200000.00, hourly_price: 50000.00, created_at: '2026-01-01 00:00:00', updated_at: '2026-04-23 21:36:33' },
            { id: 'serv_003', name: 'Técnico en climatización', slug: 'tecnico-climatizacion', description: 'Instalación, mantenimiento y reparación de aires acondicionados, sistemas de calefacción central, bombas de calor y ventilación.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":["Curso básico de refrigeración"]},{"nivel":"1-2 años","requisitos":["Experiencia comprobable","Manejo de herramientas"]},{"nivel":"3-5 años","requisitos":["Título técnico","Manejo de gases refrigerantes"]},{"nivel":"6-10 años","requisitos":["Matrícula profesional","Especialización en VRF"]},{"nivel":"+10 años","requisitos":["Certificación internacional","Gestión de proyectos HVAC"]}]'), certification_required: true, is_featured: true, is_active: true, base_price: 250000.00, hourly_price: 50000.00, created_at: '2026-01-01 00:00:00', updated_at: '2026-04-23 23:49:41' },
            { id: 'serv_004', name: 'Técnico en refrigeración', slug: 'tecnico-refrigeracion', description: 'Mantenimiento y reparación de sistemas de refrigeración comercial e industrial: cámaras frigoríficas, heladeras, freezers y vitrinas.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":["Curso básico de refrigeración"]},{"nivel":"1-2 años","requisitos":["Experiencia comprobable","Manejo de herramientas"]},{"nivel":"3-5 años","requisitos":["Título técnico","Certificación en gases refrigerantes"]},{"nivel":"6-10 años","requisitos":["Matrícula profesional","Especialización en sistemas comerciales"]},{"nivel":"+10 años","requisitos":["Certificación internacional","Gestión de equipos"]}]'), certification_required: true, is_featured: false, is_active: true, base_price: null, hourly_price: null, created_at: '2026-01-01 00:00:00', updated_at: '2026-04-23 21:49:10' },
            { id: 'serv_005', name: 'Técnico electromecánico', slug: 'tecnico-electromecanico', description: 'Mantenimiento y reparación de equipos electromecánicos: motores, bombas, generadores, sistemas de automatización y control industrial.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":["Curso básico de electromecánica"]},{"nivel":"1-2 años","requisitos":["Experiencia comprobable","Manejo de instrumentos"]},{"nivel":"3-5 años","requisitos":["Título técnico","Manejo de PLC"]},{"nivel":"6-10 años","requisitos":["Matrícula profesional","Especialización en automatización"]},{"nivel":"+10 años","requisitos":["Certificación en gestión de mantenimiento","Liderazgo técnico"]}]'), certification_required: true, is_featured: true, is_active: true, base_price: 250000.00, hourly_price: 25000.00, created_at: '2026-01-01 00:00:00', updated_at: '2026-04-23 21:37:34' },
            { id: 'serv_006', name: 'Albañil / Constructor', slug: 'albanil-constructor', description: 'Construcción, reparación y mantenimiento de estructuras civiles: mampostería, hormigón, revoques, contrapisos y refacciones.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":["Curso básico de albañilería"]},{"nivel":"1-2 años","requisitos":["Experiencia comprobable","Manejo de herramientas"]},{"nivel":"3-5 años","requisitos":["Formación técnica","Lectura de planos"]},{"nivel":"6-10 años","requisitos":["Matrícula de constructor","Gestión de obras"]},{"nivel":"+10 años","requisitos":["Ingeniería o arquitectura","Dirección de obras"]}]'), certification_required: true, is_featured: false, is_active: true, base_price: 100000.00, hourly_price: 40000.00, created_at: '2026-01-01 00:00:00', updated_at: '2026-04-23 23:48:43' },
            { id: 'serv_007', name: 'Pintor', slug: 'pintor', description: 'Pintura de interiores y exteriores, preparación de superficies, empastado, laqueado y aplicación de revestimientos decorativos.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":["Curso básico de pintura"]},{"nivel":"1-2 años","requisitos":["Experiencia comprobable","Manejo de equipos"]},{"nivel":"3-5 años","requisitos":["Técnicas avanzadas","Manejo de colores"]},{"nivel":"6-10 años","requisitos":["Especialización en revestimientos","Presupuestación"]},{"nivel":"+10 años","requisitos":["Certificación en calidad","Gestión de proyectos"]}]'), certification_required: true, is_featured: false, is_active: true, base_price: 200000.00, hourly_price: 50000.00, created_at: '2026-01-01 00:00:00', updated_at: '2026-04-23 21:35:44' },
            { id: 'serv_008', name: 'Masajista', slug: 'masajista', description: 'Distintos tipos de masajes corporales.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":[]},{"nivel":"1-2 años","requisitos":[]},{"nivel":"3-5 años","requisitos":[]},{"nivel":"6-10 años","requisitos":[]},{"nivel":"+10 años","requisitos":[]}]'), certification_required: true, is_featured: true, is_active: true, base_price: 80000.00, hourly_price: 80000.00, created_at: '2026-04-15 01:40:35', updated_at: '2026-04-23 21:36:23' },
            { id: 'serv_009', name: 'Técnico Informático', slug: 'tecnico-informatico', description: 'Profesionales capacidades y skill desde manejo de redes hasta programacion.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":[]},{"nivel":"1-2 años","requisitos":[]},{"nivel":"3-5 años","requisitos":[]},{"nivel":"6-10 años","requisitos":[]},{"nivel":"+10 años","requisitos":[]}]'), certification_required: true, is_featured: true, is_active: true, base_price: 400000.00, hourly_price: 50000.00, created_at: '2026-04-15 15:45:37', updated_at: '2026-04-15 15:45:37' },
            { id: 'serv_010', name: 'Cantante', slug: 'cantante', description: 'Servicio solicitado por Roberto Carlos', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":[]},{"nivel":"1-2 años","requisitos":[]},{"nivel":"3-5 años","requisitos":[]},{"nivel":"6-10 años","requisitos":[]},{"nivel":"+10 años","requisitos":[]}]'), certification_required: true, is_featured: true, is_active: true, base_price: 299999.99, hourly_price: 80000.00, created_at: '2026-04-17 15:26:12', updated_at: '2026-04-23 21:36:13' },
            { id: 'serv_011', name: 'Tecnico mecanico', slug: 'tecnico-mecanico', description: 'Arreglo de motores y instalaciones motorizadas.', experience_levels: JSON.parse('[{"nivel":"Sin experiencia","requisitos":[]},{"nivel":"1-2 años","requisitos":[]},{"nivel":"3-5 años","requisitos":[]},{"nivel":"6-10 años","requisitos":[]},{"nivel":"+10 años","requisitos":[]}]'), certification_required: true, is_featured: true, is_active: true, base_price: 300000.00, hourly_price: 20000.00, created_at: '2026-04-23 23:50:09', updated_at: '2026-04-27 15:05:15' }
        ], { ignoreDuplicates: true });

        // ------------------------------------------------------
        // 3. USERS
        // ------------------------------------------------------
        await User.bulkCreate([
            { id: 'usr_001', name: 'María García', email: 'maria.garcia@gmail.com', password_hash: '$2b$10$UxlAiezHOJlcWuO4aZbHr.l3DC8YIzev.FEayIQJ7GCLhYqE5tpXi', phone: '+54 9 223 411-2233', address: JSON.parse('{"calle":"Av. Colón","numero":"1234","piso":"3","depto":"B","ciudad":"Mar del Plata","provincia":"Buenos Aires","codigoPostal":"7600"}'), terms_accepted: true, is_active: true, registered_at: '2025-01-10 09:30:00', updated_at: '2026-04-14 22:18:22' },
            { id: 'usr_002', name: 'Carlos Fernández', email: 'carlosfernandez@hotmail.com', password_hash: '$2b$10$abcXYZ123abcXYZ123abcXabcXYZ123abcXYZ123abcXYZ123abcX', phone: '+54 9 223 533-4455', address: JSON.parse('{"calle":"Belgrano","numero":"3456","piso":"","depto":"","ciudad":"Mar del Plata","provincia":"Buenos Aires","codigoPostal":"7600"}'), terms_accepted: true, is_active: true, registered_at: '2025-01-25 14:15:00', updated_at: '2025-02-10 11:00:00' },
            { id: 'usr_003', name: 'Lucía Ramírez', email: 'lucia.ramirez@outlook.com', password_hash: '$2b$10$ZZZ999ZZZ999ZZZ999ZZZoZZZ999ZZZ999ZZZ999ZZZ999ZZZ999Z', phone: '', address: JSON.parse('{"calle":"San Martín","numero":"890","piso":"1","depto":"A","ciudad":"Mar del Plata","provincia":"Buenos Aires","codigoPostal":"7600"}'), terms_accepted: true, is_active: true, registered_at: '2025-02-03 18:45:00', updated_at: '2026-04-14 22:18:29' },
            { id: 'usr_004', name: 'Eric El Mas PRo', email: 'ericpro@gmail.com', password_hash: '$2b$10$a7BlJaRgfSAbqQsx2ZrSaOjQi6veayGcdBSKh5ktxUjqZoaZX60K2', phone: '', address: JSON.parse('{"calle":"","numero":"123","piso":"","depto":"","ciudad":"","provincia":"","codigoPostal":""}'), terms_accepted: true, is_active: true, registered_at: '2026-04-14 13:39:45', updated_at: '2026-04-18 02:58:36' },
            { id: 'usr_005', name: 'Jose Garcia', email: 'josegarcia@invento.com', password_hash: '$2b$10$Th5S1Ex2cUwCsiAMCk6l9eGU2dadlRDON9BXbgnRIoCGH9mjSL/LK', phone: '', address: JSON.parse('{"calle":"","numero":"","piso":"","depto":"","ciudad":"Chubut","provincia":"","codigoPostal":"8900"}'), terms_accepted: true, is_active: true, registered_at: '2026-04-14 22:19:27', updated_at: '2026-04-14 22:19:27' },
            { id: 'usr_006', name: 'Pablo Campazo', email: 'pablo@invento.com', password_hash: '$2b$10$6knI.I0rKI0bhnnsHJ.jE.IH5Mqhfoq8sb863zJ68YephNnOVgP8K', phone: '', address: JSON.parse('{"calle":"","numero":"","piso":"","depto":"","ciudad":"","provincia":"","codigoPostal":""}'), terms_accepted: true, is_active: true, registered_at: '2026-04-14 22:22:24', updated_at: '2026-04-14 22:22:24' },
            { id: 'usr_007', name: 'James Bond', email: 'admin@ee.com', password_hash: '$2b$10$6knI.I0rKI0bhnnsHJ.jE.IH5Mqhfoq8sb863zJ68YephNnOVgP8K', phone: '123123123', address: JSON.parse('{"calle":"","numero":"","piso":"","depto":"","ciudad":"","provincia":"","codigoPostal":""}'), terms_accepted: true, is_active: true, registered_at: '2026-04-14 22:22:24', updated_at: '2026-04-27 18:53:06' }
        ], { ignoreDuplicates: true });

        // ------------------------------------------------------
        // 4. PRODUCTS
        // ------------------------------------------------------
        await Product.bulkCreate([
            { id: 'prod_001', name: 'Aire Acondicionado Split 4500 Frigorías', sku: 'AC-4500-SIL', category_id: 'cat_001', description: 'Aire acondicionado split de 4500 frigorías, ideal para ambientes de 20-25 m² con eficiencia energética A++ y función frío/calor.', characteristics: [], image: 'https://ejemplo.com/productos/ac-4500.jpg', images: [], colors: ['Blanco,Negro'], sizes: ['3000 BTU,4500 BTU,6000 BTU'], price: 199999.00, original_price: 235000.00, installation_available: true, installation_service_id: 'serv_003', rating_value: 4.5, rating_count: 128, is_active: true, created_at: '2025-01-15 10:00:00', updated_at: '2026-04-24 04:30:25' },
            { id: 'prod_002', name: 'Taladro Percutor Inalámbrico 20V', sku: 'TAL-20V-INA', category_id: 'cat_002', description: 'Taladro percutor inalámbrico de 20V con batería de litio de larga duración. Incluye maletín, 2 baterías y cargador rápido.', characteristics: ['Motor brushless de alta eficiencia', '20V batería de ión litio 4Ah', '2 velocidades: 0-450 / 0-1800 rpm', 'Par máximo 65 Nm', 'Portabrocas 13mm con bloqueo automático', 'Luz LED de trabajo', 'Incluye 2 baterías + cargador rápido + maletín'], image: 'https://ejemplo.com/productos/taladro-20v.jpg', images: ['https://ejemplo.com/productos/taladro-20v-frente.jpg', 'https://ejemplo.com/productos/taladro-20v-maleta.jpg'], colors: ['Negro/Verde', 'Negro/Rojo', 'Azul/Negro'], sizes: [], price: 109999.00, original_price: 110000.00, installation_available: false, installation_service_id: null, rating_value: 4.8, rating_count: 64, is_active: true, created_at: '2025-01-20 11:00:00', updated_at: '2026-04-11 02:56:44' },
            { id: 'prod_003', name: 'Kit Lámparas LED GU10 6W Luz Cálida x10', sku: 'LED-GU10-6W-CX10', category_id: 'cat_004', description: 'Pack de 10 lámparas LED GU10 de 6W con luz cálida 3000K. Reemplazo directo de dicroicas halógenas de 50W. Vida útil 25.000 horas.', characteristics: ['Potencia: 6W (equivale a 50W halógena)', 'Temperatura de color: 3000K (luz cálida)', 'Flujo luminoso: 500 lm', 'Vida útil: 25.000 horas', 'Base GU10 estándar', 'No requiere transformador', 'Apto para exterior cubierto'], image: 'https://ejemplo.com/productos/led-gu10.jpg', images: ['https://ejemplo.com/productos/led-gu10-pack.jpg', 'https://ejemplo.com/productos/led-gu10-instalada.jpg'], colors: [], sizes: ['3000K cálida', '6500K fría'], price: 12999.00, original_price: 0.00, installation_available: true, installation_service_id: 'serv_001', rating_value: 4.2, rating_count: 211, is_active: true, created_at: '2025-02-01 08:30:00', updated_at: '2026-04-24 04:31:04' },
            { id: 'prod_004', name: 'Termotanque Eléctrico 80L', sku: 'TT-ELEC-80L', category_id: 'cat_005', description: 'Termotanque eléctrico de 80 litros con cuba de acero vitrificado y ánodo de magnesio. Apto para 3-4 personas.', characteristics: ['Capacidad: 80 litros', 'Potencia: 1500W / 220V', 'Cuba de acero vitrificado de alta resistencia', 'Ánodo de magnesio anticorrosión', 'Termostato regulable 35°C - 75°C', 'Válvula de seguridad incluida', 'Garantía 5 años en La matanza'], image: 'https://ejemplo.com/productos/termotanque-80l.jpg', images: ['https://ejemplo.com/productos/termotanque-80l-frente.jpg', 'https://ejemplo.com/productos/termotanque-80l-instalado.jpg'], colors: ['Blanco'], sizes: ['50L', '80L', '100L'], price: 149999.00, original_price: 175000.00, installation_available: true, installation_service_id: 'serv_002', rating_value: 4.6, rating_count: 47, is_active: true, created_at: '2025-02-10 13:00:00', updated_at: '2026-04-24 04:30:52' },
            { id: 'prod_005', name: 'Ceramicos Porcelanato 25x25', sku: 'CP-01-12302', category_id: 'cat_008', description: 'Ceramicos para piso, ideal para:\r\nCocinas\r\nComedores\r\nLiving\r\nSala de Estar', characteristics: [], image: '-', images: [], colors: ['Rojo y Negro', 'Negro y Rojo', 'Celeste y Blanco'], sizes: ['x100Unidades', 'x500Unidades'], price: 1000.00, original_price: 5000.00, installation_available: true, installation_service_id: 'serv_006', rating_value: 0.0, rating_count: 0, is_active: true, created_at: '2026-04-10 21:59:36', updated_at: '2026-04-24 04:31:15' },
            { id: 'prod_006', name: 'Lampara Oveja', sku: 'ME-123-12312', category_id: 'cat_004', description: 'Lampara con forma de oveja, ideal para habitaciones infantiles. Puede hablar.', characteristics: ['Textura con materiales reciclados.', 'Ideal para habitaciones infantiles', 'Puede hablar.'], image: '.', images: [], colors: ['Negra', 'blanca', 'Rojo'], sizes: ['12.000Volts'], price: 425211.00, original_price: 1000.00, installation_available: false, installation_service_id: null, rating_value: 0.0, rating_count: 0, is_active: true, created_at: '2026-04-10 22:02:33', updated_at: '2026-04-12 05:39:03' },
            { id: 'prod_007', name: 'Descontracturante de espalda.', sku: 'MD-012-1232', category_id: 'cat_011', description: 'Descontracturante de espalda usando las manos u herramientas para la correcta y reconformante experiencia al usuario.', characteristics: [], image: '.', images: [], colors: [], sizes: [], price: 150000.00, original_price: 0.00, installation_available: true, installation_service_id: 'serv_008', rating_value: 0.0, rating_count: 0, is_active: true, created_at: '2026-04-12 05:45:21', updated_at: '2026-04-24 04:32:09' },
            { id: 'prod_008', name: 'Como hacer helado', sku: 'Cu-01-1232', category_id: 'cat_010', description: 'Elaboracion y explicaciones tecnicas de los procesos para la leaboracion de helado artesanal.', characteristics: [], image: '.', images: [], colors: [], sizes: [], price: 150000.00, original_price: 200000.00, installation_available: true, installation_service_id: 'serv_010', rating_value: 0.0, rating_count: 0, is_active: true, created_at: '2026-04-12 05:49:31', updated_at: '2026-04-24 04:32:29' },
            { id: 'prod_009', name: 'Aspirador de Gatos', sku: 'CAT-123-12312', category_id: 'cat_012', description: 'Revolucionario e innovador aspirador de gatos super silencioso.', characteristics: [], image: '.', images: [], colors: [], sizes: [], price: 50000.00, original_price: 100000.00, installation_available: false, installation_service_id: null, rating_value: 0.0, rating_count: 0, is_active: true, created_at: '2026-04-14 22:56:11', updated_at: '2026-04-24 03:04:50' },
            { id: 'prod_010', name: 'Inodoro Bari Largo', sku: 'AK-12-12331', category_id: 'cat_005', description: 'Elegí el Inodoro Bari Largo de Ferrum y transformá tu baño en un espacio elegante y funcional. Su diseño moderno y sus características te brindan la comodidad y el estilo que buscás en tu casa.', characteristics: [], image: 'https://blaistenio.vtexassets.com/arquivos/ids/155598-1600-1600?v=638342802419600000&width=1600&height=1600&aspect=true', images: [], colors: ['Blanco'], sizes: ['S'], price: 1890.09, original_price: 25000.00, installation_available: true, installation_service_id: 'serv_002', rating_value: 0.0, rating_count: 0, is_active: true, created_at: '2026-04-23 20:47:09', updated_at: '2026-04-27 14:59:50' },
            { id: 'prod_011', name: 'Ferrum ECO - Bacha Persis con esmalte reciclado', sku: 'PRS-BH-022-12', category_id: 'cat_005', description: 'Innovación en la utilización de esmalte reciclado. Se recomienda el uso de griferías FV.', characteristics: [], image: 'https://ferrum.com/pub/media/catalog/product/cache/723de03bc8ecfa836485d5b2e3f2ed4a/b/a/bacha-apoyo-persis-ferrum-bacha-esmalte-reciclado-satinado-prs-bh-022-vp-b_copia_1.jpg', images: [], colors: [], sizes: [], price: 124000.00, original_price: 200000.00, installation_available: true, installation_service_id: 'serv_002', rating_value: 0.0, rating_count: 0, is_active: true, created_at: '2026-04-24 02:57:42', updated_at: '2026-04-24 04:32:48' },
            { id: 'prod_012', name: 'Calefactor Coppens', sku: 'ED6346', category_id: 'cat_005', description: 'Calefactor Coppens C40BIPAM 4000TB 4000Kcal para espacios de hasta 30 m², con salida lateral izquierda, combina rendimiento y eficiencia para mantener el ambiente cálido de forma constante.', characteristics: [], image: 'https://cetrogar.vtexassets.com/arquivos/ids/163439-768-auto/Calefactor-C40BIPAM-4000TB-4000Kcal-30m2-izquierda.webp?v=639113902119800000&quality=8', images: [], colors: [], sizes: [], price: 309.999, original_price: 327.999, installation_available: true, installation_service_id: 'serv_002', rating_value: 0.0, rating_count: 0, is_active: true, created_at: '2026-04-27 15:01:34', updated_at: '2026-04-27 15:02:07' }
        ], { ignoreDuplicates: true });

        // ------------------------------------------------------
        // 5. PROFESSIONALS
        // ------------------------------------------------------
        await Professional.bulkCreate([
            { id: 'prof_001', name: 'Juan Carlos Rodríguez', license_number: 'MP-04578', profession: 'Técnico en climatización', service_id: 'serv_003', custom_service: null, service_status: 'aprobado', experience_years: 8, certification_url: '/uploads/certificados/mp-04578_climatizacion.pdf', certification_verified: true, validation_date: '2025-01-15 10:00:00', validated_by: 'admin@ee.com', admin_observation: 'Certificación válida y experiencia comprobada.', email: 'jcrodriguez@gmail.com', phone: '+54 9 223 456-7890', availability: JSON.parse('{"lunes":{"manana":true,"tarde":true},"martes":{"manana":true,"tarde":true},"miercoles":{"manana":true,"tarde":true},"jueves":{"manana":true,"tarde":true},"viernes":{"manana":true,"tarde":true}}'), rating_value: 4.8, rating_count: 23, jobs_completed: 23, is_active: true, created_at: '2025-01-10 09:00:00', updated_at: '2026-04-14 21:43:00' },
            { id: 'prof_002', name: 'Roberto Sánchez', license_number: 'MN-12345', profession: 'Electricista', service_id: 'serv_001', custom_service: null, service_status: 'aprobado', experience_years: 5, certification_url: '/uploads/certificados/mn-12345_electricista.pdf', certification_verified: true, validation_date: '2026-04-27 15:04:08', validated_by: 'admin@ee.com', admin_observation: null, email: 'roberto.sanchez@outlook.com', phone: '+54 9 223 567-8901', availability: JSON.parse('{"lunes":{"manana":true,"tarde":true},"martes":{"manana":true,"tarde":true},"miercoles":{"manana":true,"tarde":true},"jueves":{"manana":true,"tarde":true},"viernes":{"manana":true,"tarde":true}}'), rating_value: 4.5, rating_count: 15, jobs_completed: 15, is_active: true, created_at: '2025-01-18 10:00:00', updated_at: '2026-04-27 15:04:08' },
            { id: 'prof_003', name: 'Alejandro López', license_number: 'MP-09871', profession: 'Plomero / Gasista', service_id: 'serv_002', custom_service: null, service_status: 'aprobado', experience_years: 11, certification_url: '/uploads/certificados/mp-09871_plomeria.pdf', certification_verified: true, validation_date: '2026-04-23 00:59:31', validated_by: 'admin@ee.com', admin_observation: null, email: 'alopez.plomeria@gmail.com', phone: '+54 9 223 678-9012', availability: JSON.parse('{"lunes":{"manana":true,"tarde":true},"martes":{"manana":true,"tarde":true},"miercoles":{"manana":true,"tarde":true},"jueves":{"manana":true,"tarde":true},"viernes":{"manana":true,"tarde":true}}'), rating_value: 4.9, rating_count: 38, jobs_completed: 38, is_active: true, created_at: '2024-12-01 08:00:00', updated_at: '2026-04-23 00:59:31' },
            { id: 'prof_004', name: 'Marcela Torres', license_number: 'MP-33210', profession: 'Técnico en refrigeración', service_id: 'serv_004', custom_service: null, service_status: 'aprobado', experience_years: 3, certification_url: '/uploads/certificados/mp-33210_refrigeracion.pdf', certification_verified: true, validation_date: '2026-04-15 15:42:40', validated_by: 'admin@ee.com', admin_observation: 'Certificacion adecuada.\r\nSe da de alta solicitud de nuevo servicio.', email: 'marcela.torres.tec@gmail.com', phone: '', availability: JSON.parse('{"lunes":{"manana":false,"tarde":true},"martes":{"manana":false,"tarde":false},"miercoles":{"manana":true,"tarde":false},"jueves":{"manana":true,"tarde":false},"viernes":{"manana":false,"tarde":true}}'), rating_value: 0.0, rating_count: 0, jobs_completed: 0, is_active: true, created_at: '2025-02-28 14:00:00', updated_at: '2026-04-15 15:42:40' },
            { id: 'prof_005', name: 'Marta Stuart', license_number: 'MN-02938', profession: 'Pintor', service_id: null, custom_service: 'Pintura artística y decorativa', service_status: 'rechazado', experience_years: 6, certification_url: null, certification_verified: false, validation_date: '2026-04-17 15:26:55', validated_by: 'admin@ee.com', admin_observation: 'Marta es cantante.', email: 'marta@stuart.org', phone: '', availability: JSON.parse('{"lunes":{"manana":true,"tarde":false},"martes":{"manana":true,"tarde":false},"miercoles":{"manana":true,"tarde":false},"jueves":{"manana":true,"tarde":false},"viernes":{"manana":true,"tarde":false}}'), rating_value: 0.0, rating_count: 0, jobs_completed: 0, is_active: true, created_at: '2026-04-14 21:47:51', updated_at: '2026-04-17 15:26:55' },
            { id: 'prof_006', name: 'Raul Obrero', license_number: 'MP-12523', profession: '', service_id: 'serv_002', custom_service: null, service_status: 'aprobado', experience_years: 3, certification_url: null, certification_verified: true, validation_date: '2026-04-24 22:53:56', validated_by: 'admin@ee.com', admin_observation: null, email: 'raulpc@gmail.com', phone: '', availability: JSON.parse('{"lunes":{"manana":true,"tarde":true},"martes":{"manana":true,"tarde":true},"miercoles":{"manana":true,"tarde":true},"jueves":{"manana":true,"tarde":true},"viernes":{"manana":true,"tarde":true}}'), rating_value: 0.0, rating_count: 0, jobs_completed: 0, is_active: true, created_at: '2026-04-15 15:31:21', updated_at: '2026-04-24 22:53:56' },
            { id: 'prof_007', name: 'Roberto Carlos', license_number: 'MN-00938', profession: '', service_id: 'serv_010', custom_service: null, service_status: 'aprobado', experience_years: 16, certification_url: null, certification_verified: true, validation_date: '2026-04-24 22:41:07', validated_by: 'admin@ee.com', admin_observation: null, email: 'robertocarlos@gmail.com', phone: '', availability: JSON.parse('{"lunes":{"manana":true,"tarde":true},"martes":{"manana":true,"tarde":true},"miercoles":{"manana":true,"tarde":true},"jueves":{"manana":true,"tarde":true},"viernes":{"manana":true,"tarde":true}}'), rating_value: 0.0, rating_count: 0, jobs_completed: 0, is_active: true, created_at: '2026-04-17 15:14:47', updated_at: '2026-04-24 22:41:07' },
            { id: 'prof_008', name: 'Mario Pergolini', license_number: 'MP-541232', profession: '', service_id: 'serv_001', custom_service: null, service_status: 'aprobado', experience_years: 5, certification_url: null, certification_verified: true, validation_date: '2026-04-24 22:53:36', validated_by: 'admin@ee.com', admin_observation: null, email: 'marito@hmotm.com', phone: '', availability: JSON.parse('{"lunes":{"manana":true,"tarde":true},"martes":{"manana":true,"tarde":true},"miercoles":{"manana":true,"tarde":true},"jueves":{"manana":true,"tarde":true},"viernes":{"manana":true,"tarde":true}}'), rating_value: 0.0, rating_count: 0, jobs_completed: 0, is_active: true, created_at: '2026-04-24 22:45:05', updated_at: '2026-04-24 22:53:36' },
            { id: 'prof_009', name: 'Jorge Castro', license_number: 'MN-02931', profession: '', service_id: 'serv_011', custom_service: null, service_status: 'aprobado', experience_years: 4, certification_url: null, certification_verified: false, validation_date: null, validated_by: null, admin_observation: null, email: 'castro@gmail.com', phone: '', availability: JSON.parse('{"lunes":{"manana":true,"tarde":false},"martes":{"manana":true,"tarde":false},"miercoles":{"manana":true,"tarde":false},"jueves":{"manana":true,"tarde":false},"viernes":{"manana":true,"tarde":false}}'), rating_value: 0.0, rating_count: 0, jobs_completed: 0, is_active: true, created_at: '2026-04-27 15:03:47', updated_at: '2026-04-27 15:03:47' }
        ], { ignoreDuplicates: true });

        // ------------------------------------------------------
        // 6. BOOKINGS
        // ------------------------------------------------------
        await Booking.bulkCreate([
            { id: 'res_001', user_id: null, session_id: 'obhopuKGczM9xkdLHbx-YMqKOZ0dCFgf', created_at: '2026-04-21 14:19:40', updated_at: '2026-04-21 14:19:40' },
            { id: 'res_002', user_id: 'usr_007', session_id: null, created_at: '2026-04-21 18:41:40', updated_at: '2026-04-28 16:57:47' },
            { id: 'res_003', user_id: 'usr_004', session_id: null, created_at: '2026-04-29 11:55:39', updated_at: '2026-04-29 17:39:35' }
        ], { ignoreDuplicates: true });

        // ------------------------------------------------------
        // 7. BOOKING ITEMS
        // ------------------------------------------------------
        await BookingItem.bulkCreate([
            { id: 'item_1776781180643_ojvy', booking_id: 'res_001', type: 'product', product_id: 'prod_004', service_id: null, quantity: 1, unit_price: 149999.00, name: 'Termotanque Eléctrico 80L', professional_id: null, installation_date: null, installation_time: null, created_at: '2026-04-21 14:19:40', updated_at: '2026-04-21 14:19:40' },
            { id: 'item_1777304072011_aema', booking_id: 'res_002', type: 'service', product_id: null, service_id: 'serv_002', quantity: 3, unit_price: 0.00, name: 'Plomero / Gasista', professional_id: 'prof_006', installation_date: '2026-04-22', installation_time: 'manana', created_at: '2026-04-21 18:41:40', updated_at: '2026-04-28 16:57:47' },
            { id: 'item_1777484375775_dgt3', booking_id: 'res_003', type: 'combo', product_id: 'prod_001', service_id: 'serv_003', quantity: 1, unit_price: 449999.00, name: 'Aire Acondicionado Split 4500 Frigorías + Servicio (Técnico en climatización)', professional_id: 'prof_001', installation_date: '2026-04-30', installation_time: 'manana', created_at: '2026-04-29 11:55:39', updated_at: '2026-04-29 17:39:35' }
        ], { ignoreDuplicates: true });

        // ------------------------------------------------------
        // 8. SERVICE REQUESTS
        // ------------------------------------------------------
        await ServiceRequest.bulkCreate([
            { id: 'sol_001', professional_id: 'prof_005', requested_service: 'Instalador de paneles solares', description: 'Especialista en energía solar fotovoltaica', status: 'rechazado', request_date: '2026-04-14 10:00:00', response_date: '2026-04-15 15:41:36', response_admin: 'admin@ee.com' },
            { id: 'sol_002', professional_id: 'prof_006', requested_service: 'Reparador de PC', description: 'Instalación de Software, arreglos de hardware.', status: 'rechazado', request_date: '2026-04-15 15:31:21', response_date: '2026-04-17 14:47:45', response_admin: 'admin@ee.com' },
            { id: 'sol_003', professional_id: 'prof_007', requested_service: 'Cantante', description: 'Cantante para eventos.', status: 'aprobado', request_date: '2026-04-17 15:14:28', response_date: '2026-04-17 15:26:13', response_admin: 'admin@ee.com' },
            { id: 'sol_004', professional_id: null, requested_service: 'Cantante', description: 'Cantante para eventos.', status: 'pendiente', request_date: '2026-04-17 15:14:47', response_date: null, response_admin: null }
        ], { ignoreDuplicates: true });
    },

    async down(queryInterface, Sequelize) {
        // Eliminar en orden inverso
        await ServiceRequest.destroy({ truncate: true, cascade: false });
        await BookingItem.destroy({ truncate: true, cascade: false });
        await Booking.destroy({ truncate: true, cascade: false });
        await Professional.destroy({ truncate: true, cascade: false });
        await Product.destroy({ truncate: true, cascade: false });
        await User.destroy({ truncate: true, cascade: false });
        await Service.destroy({ truncate: true, cascade: false });
        await Category.destroy({ truncate: true, cascade: false });
    }
};